### ISSUE TITLE
Where can I get esmi_mailbox_nda.h?

### ISSUE THREAD

**Issue by tajima6623** [AMDESE/OpenBMC#4]
I got two errors when building OpenBMC.
Both errors say that esmi_mailbox_nda.h is missing.

| /home/tajima/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/cpu-info/1.0-r0/git/src/cpu_info.cpp:25:10: fatal error: esmi_mailbox_nda.h: No such file or directory
|    25 | #include "esmi_mailbox_nda.h"
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
|

| /home/tajima/OpenBMC/build/sp5/tmp/work/armv7ahf-vfpv4d16-openbmc-linux-gnueabi/amd-ras/1.0-r0/git/src/main.cpp:39:10: fatal error: esmi_mailbox_nda.h: No such file or directory
|    39 | #include "esmi_mailbox_nda.h"
|       |          ^~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
|

Where can I get esmi_mailbox_nda.h?

**Comment by tajima6623** [comment]
Thank you for your reply.
I cannot access https://github.com/amd/apml_library. 
I get 404 not found.

**Comment by tajima6623** [comment]
So, I modified amd-apml.bb.
OpenBMC/meta-amd/meta-common/recipes-amd/amd-apml/amd-apml.bb:
```
#SRC_URI += "git://git@github.com/amd/apml_library.git;protocol=ssh"
SRC_URI += "git://git@github.com/amd/esmi_oob_library.git;protocol=ssh"
```

**Comment by tajima6623** [comment]
I found the following issue.

https://github.com/AMDESE/amd-bmc-ras/issues/51

I would like permission to https://github.com/amd/apml_library
How is it given by the AMD Customer Team?

**Comment by supven01** [comment]
[AMD Official Use Only - General]

Work with your AMD customer rep and provide your GitHub ID and email.
AMD customer rep will raise an IT ticket on your behalf to provide access to NDA repo.

Thanks,
Supreeth Venkatesh
System Manageability Architect  |  AMD
Server Software
***@***.***

**Comment by tajima6623** [comment]
We asked AND's customer representative to grant us access to the NDA repository. 
We can now access https://github.com/amd/apml_library successfully. 
Thank you very much.
